# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

APPLY_FIXES: none
# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling formats will be disabled by default
ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
  -   TERRAFORM_TERRASCAN
#DISABLE:
  #- CLOUDFORMATION
  # - COPYPASTE # Uncomment to disable checks of excessive copy-pastes
  # - SPELL # Uncomment to disable checks of spelling mistakes
#DISABLE_LINTERS:
  #- JSON_PRETTIER
#DISABLE_ERRORS_LINTERS:
  #- PYTHON_BANDIT
#PRINT_ALL_FILES: false
TERRAFORM_TFLINT_PRE_COMMANDS: 
  - command: "terraform init -backend=false"

TERRAFORM_TFLINT_UNSECURED_ENV_VARIABLES:
  - GITHUB_TOKEN # Can contain string only, not regex